import type { Locale } from "./config";

const en = {
  welcome: "A little closer to your next escape.", intro: "Discover homes in your trusted circles, make plans, and feel at home somewhere new.",
  eyebrow: "Your Kinami", explore: "Find your next stay", exploreBody: "Homes shared by the people in your circles.",
  search: "Where would you like to go?", searchPlaceholder: "Search city, country or home", all: "All circles", circleFilter: "Circle", results: "homes to explore", noResults: "No homes match your search.", reset: "Clear filters", noHomes: "Your next stay starts with your circle.", noHomesBody: "Join a circle with an invite code, or create one and invite people you trust to share their homes.",
  next: "Your next step", join: "Have an invite code?", create: "Start a new circle", circles: "Your circles", circleHint: "Private spaces for your people and their homes.", example: "Explore an example", exampleBody: "New here? Take a look around a sample circle. These homes are for trying Kinami.",
  addHome: "Share your home", addHomeBody: "Give your circle a reason to start planning. Add your home and the dates you can host.", manageHome: "Keep your home up to date", manageHomeBody: "Let your circle know when your home is free for their next escape.", dates: "Update availability", requests: "Your exchanges", requestsBody: "Keep plans moving. Read requests, agree dates and continue your conversations.", pending: "requests awaiting your reply", viewRequests: "View requests", own: "Your home", details: "View home", noDates: "Ask about dates", available: "Next shared dates", sample: "Example home", how: "See how it works", invitation: "Have an invitation? You can enter your code after signing in.", preview: "A glimpse of life in your circle", previewNote: "Sample homes · your real circle stays private", privacy: "Private by design", browse: "Explore homes", back: "Back to your circles", requestIntro: "Everything you need to turn a conversation into your next stay.", reply: "Needs your reply", emptyRequests: "Your next exchange starts with a home you love.", homeNav: "Explore", sectionNav: "On this page", members: "People", homes: "Homes", invite: "Invite friends", start: "Get started", learn: "A home swap, in three simple steps.",
};
type Copy = { [K in keyof typeof en]: string };
const es: Copy = {
  welcome: "Tu próxima escapada empieza cerca.", intro: "Descubre las casas de tus círculos, haz planes y siéntete en casa en un lugar nuevo.", eyebrow: "Tu Kinami", explore: "Encuentra tu próxima estancia", exploreBody: "Casas que comparten las personas de tus círculos.", search: "¿A dónde te gustaría ir?", searchPlaceholder: "Busca ciudad, país o casa", all: "Todos los círculos", circleFilter: "Círculo", results: "casas por descubrir", noResults: "Ninguna casa coincide con tu búsqueda.", reset: "Borrar filtros", noHomes: "Tu próxima estancia empieza con tu círculo.", noHomesBody: "Únete con un código de invitación o crea un círculo e invita a personas de confianza a compartir sus casas.", next: "Tu siguiente paso", join: "¿Tienes un código de invitación?", create: "Crear un círculo", circles: "Tus círculos", circleHint: "Espacios privados para tu gente y sus casas.", example: "Explora un ejemplo", exampleBody: "¿Acabas de llegar? Descubre un círculo de ejemplo. Estas casas son para probar Kinami.", addHome: "Comparte tu casa", addHomeBody: "Da a tu círculo un motivo para hacer planes. Añade tu casa y las fechas en las que puedes recibir visitas.", manageHome: "Pon tu casa al día", manageHomeBody: "Dile a tu círculo cuándo está libre tu casa para su próxima escapada.", dates: "Actualizar disponibilidad", requests: "Tus intercambios", requestsBody: "Haz avanzar tus planes. Revisa solicitudes, acuerda fechas y continúa tus conversaciones.", pending: "solicitudes esperan tu respuesta", viewRequests: "Ver solicitudes", own: "Tu casa", details: "Ver casa", noDates: "Consulta las fechas", available: "Próximas fechas compartidas", sample: "Casa de ejemplo", how: "Cómo funciona", invitation: "¿Tienes una invitación? Podrás introducir tu código después de entrar.", preview: "Así se vive en tu círculo", previewNote: "Casas de ejemplo · tu círculo real es privado", privacy: "Privado desde el principio", browse: "Explorar casas", back: "Volver a tus círculos", requestIntro: "Todo lo que necesitas para convertir una conversación en tu próxima estancia.", reply: "Necesita tu respuesta", emptyRequests: "Tu próximo intercambio empieza con una casa que te guste.", homeNav: "Explorar", sectionNav: "En esta página", members: "Personas", homes: "Casas", invite: "Invitar amigos", start: "Empezar", learn: "Un intercambio, en tres pasos sencillos.",
};
const ca: Copy = {
  welcome: "La teva pròxima escapada comença a prop.", intro: "Descobreix les cases dels teus cercles, fes plans i sent-te a casa en un lloc nou.", eyebrow: "El teu Kinami", explore: "Troba la teva pròxima estada", exploreBody: "Cases que comparteixen les persones dels teus cercles.", search: "On t’agradaria anar?", searchPlaceholder: "Cerca ciutat, país o casa", all: "Tots els cercles", circleFilter: "Cercle", results: "cases per descobrir", noResults: "Cap casa coincideix amb la cerca.", reset: "Esborra els filtres", noHomes: "La teva pròxima estada comença amb el teu cercle.", noHomesBody: "Uneix-t’hi amb un codi d’invitació o crea un cercle i convida persones de confiança a compartir casa seva.", next: "El teu següent pas", join: "Tens un codi d’invitació?", create: "Crea un cercle", circles: "Els teus cercles", circleHint: "Espais privats per a la teva gent i les seves cases.", example: "Explora un exemple", exampleBody: "Acabes d’arribar? Descobreix un cercle d’exemple. Aquestes cases són per provar Kinami.", addHome: "Comparteix casa teva", addHomeBody: "Dona al teu cercle un motiu per fer plans. Afegeix casa teva i les dates en què pots rebre visites.", manageHome: "Posa casa teva al dia", manageHomeBody: "Digues al teu cercle quan està lliure casa teva per a la seva pròxima escapada.", dates: "Actualitza la disponibilitat", requests: "Els teus intercanvis", requestsBody: "Fes avançar els plans. Revisa sol·licituds, acorda dates i continua les converses.", pending: "sol·licituds esperen la teva resposta", viewRequests: "Veure sol·licituds", own: "Casa teva", details: "Veure casa", noDates: "Consulta les dates", available: "Pròximes dates compartides", sample: "Casa d’exemple", how: "Com funciona", invitation: "Tens una invitació? Podràs introduir el codi després d’entrar.", preview: "Així es viu al teu cercle", previewNote: "Cases d’exemple · el teu cercle real és privat", privacy: "Privat des del principi", browse: "Explora cases", back: "Torna als teus cercles", requestIntro: "Tot el que necessites per convertir una conversa en la teva pròxima estada.", reply: "Necessita la teva resposta", emptyRequests: "El teu pròxim intercanvi comença amb una casa que t’agradi.", homeNav: "Explora", sectionNav: "En aquesta pàgina", members: "Persones", homes: "Cases", invite: "Convida amics", start: "Comença", learn: "Un intercanvi, en tres passos senzills.",
};
export function experienceCopy(locale: Locale): Copy { return { en, es, ca }[locale]; }
